#configurando postgre para subir em um container

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:  #var de ambiente, ver no site do POSTGRESQL
      - POSTGRESQL_DATABASE=
      - POSTGRESQL_USERNAME=
      - POSTGRESQL_PASSWORD=
    volumes:
      - ./data:/bitnami/postgresql   #salva na pasta data do composer


